### ISSUE TITLE
API has no model

### ISSUE THREAD

**Issue by JacobAMason** [henryjr1/DelterAirlinesTeam3#4]
I somehow missed this earlier, but the API has no model. There is no return type for any of the available endpoints.

**Comment by aqd14** [comment]
We fixed and updated APIs to ver 1.1

**Comment by JacobAMason** [comment]
I still don't see any model at https://app.swaggerhub.com/apis/DelterArlines/DelterAirlinesAPI/1.1.1

**Comment by willtnobles** [comment]
There should be a model now at https://app.swaggerhub.com/apis/DelterArlines/DelterAirlinesAPI/1.2.1

**Comment by BlakeHolifield** [comment]
The model seems to be correct, but the timestamps are off spec. 
http://35.193.165.105/api/v1.1/flights 
The flights in this request have start and end date formats of `2017-12-30T21:50:00+00:00` when the spec requires a date formats to match `2017-11-30T12:00:00`. Removing the `+00:00` after should fix the issue. 

The below api call to search for a flight also returns a flights array with 2 empty objects. This could be the result of the timestamp issue. 

[http://35.193.165.105/api/v1.1/Flight-Search?fromLocation=Starkville, MS&toLocation=Atlanta, GA&startDate=2017-12-30T21:50:00&endDate=2017-01-03T12:10:00]() 

We are not seeing any data returns for that date range, and we should be. The only thing the api returns is the empty flights array.

**Comment by aqd14** [comment]
Hey Blake, thanks for the comment. 

Currently we support two datetime format:

1. YYYY-mm-dd
http://35.193.165.105/api/v1.1/Flight-Search?fromLocation=Starkville,%20MS&toLocation=Atlanta,%20GA&startDate=2017-12-30&endDate=2018-01-01

2. YYYY-mm-ddThh:dd (No specified second needed, we got this format from APIs requirement Dr. Williams posted while ago)
http://35.193.165.105/api/v1.1/Flight-Search?fromLocation=Starkville,%20MS&toLocation=Atlanta,%20GA&startDate=2017-11-30T15:40&endDate=2017-12-04T08:25

> The model seems to be correct, but the timestamps are off spec.
http://35.193.165.105/api/v1.1/flights
The flights in this request have start and end date formats of 2017-12-30T21:50:00+00:00 when the spec requires a date formats to match 2017-11-30T12:00:00. Removing the +00:00 after should fix the issue.

Is this important? You just need to make the correct API calls (stated above) and the results will be return. I think you can handle the formatting in your side.Although we can modify in our side if you want.

**Comment by JacobAMason** [comment]
It is vital that the date time formats match the spec exactly since that, along with location, are pieces of data that must be submitted to every team's endpoints.

**Comment by aqd14** [comment]
Ok, I will update format for the returned object.

How about the API call? Does this include second? Below is example from Dr. Williams

> /inventory?startDate=2017-11-14T00:00&endDate=2017-11-14T23:59&lo
cation=Starkville,%20MS

**Comment by BlakeHolifield** [comment]
> YYYY-mm-ddThh:dd (No specified second needed, we got this format from APIs requirement Dr. Williams posted while ago)
http://35.193.165.105/api/v1.1/Flight-Search?fromLocation=Starkville,%20MS&toLocation=Atlanta,%20GA&startDate=2017-11-30T15:40&endDate=2017-12-04T08:25

The root cause of our issue is that this call seems to match the parameters given exactly. The startDate and endDate are intended to filter by the range of those dates. 

> Below is example from Dr. Williams
/inventory?startDate=2017-11-14T00:00&endDate=2017-11-14T23:59&lo
cation=Starkville,%20MS

This is a mistake in our document. The timestamp does need the end seconds, so `2017-11-14T00:00:00` matches the actual spec. Sorry about that!

**Comment by aqd14** [comment]
Hey Blake, the new formatting is up now. Please help us check. Thanks!

**Comment by BlakeHolifield** [comment]
Formatting looks good now. Looking into the filter ranges to double check that they're working correctly.

**Comment by BlakeHolifield** [comment]
Everything is working correctly now. I really appreciate your quick responses. Thanks!
